name: Move Jira Card

on:
  repository_dispatch:
    types: [MOVE_CARD]

permissions:
  contents: read

jobs:
  move-card:
    runs-on: ubuntu-latest
    steps:
      - name: Extract issue details
        id: extract
        run: |
          echo "Extracting issue details"
          echo "Issue Key: ${{ github.event.client_payload.issue_key }}"
          echo "Transition ID: ${{ github.event.client_payload.transition_id }}"
          echo "ISSUE_KEY=${{ github.event.client_payload.issue_key }}" >> $GITHUB_ENV

      - name: Get open pull requests
        id: get_prs
        run: |
          PRS=$(curl -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/lolgraphics/lolgraphs.api/pulls)
          echo "::set-output name=prs::$PRS"
